#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from statistics import mean
from typing import Any


TARGET_MINER = "hopper_15"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Summarize GridPool pool-hopping sweep output into a claim-oriented report.",
    )
    parser.add_argument("--csv", required=True, type=Path, help="sweep_results.csv from run_sweep.py")
    parser.add_argument("--out", required=True, type=Path, help="Markdown report path to write")
    parser.add_argument("--target-miner", default=TARGET_MINER, help="Miner ID to treat as the hopper")
    args = parser.parse_args()

    rows = read_rows(args.csv)
    if not rows:
        raise ValueError(f"No rows found in {args.csv}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_report(rows, args.target_miner, args.csv), encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def build_report(rows: list[dict[str, str]], target_miner: str, source: Path) -> str:
    variants = sorted({row["variant"] for row in rows})
    strategies = sorted(
        {
            row["result_label"]
            for row in rows
            if row.get("entity_type") == "paired_delta" and row.get("entity") == target_miner
        }
    )
    fees = sorted({row.get("param_external_fee_rate", "") for row in rows}, key=floatish)
    modes = sorted({row.get("param_external_payout_mode", "deterministic_fpps") for row in rows})

    lines = [
        "# GridPool Pool-Hopping Sweep Analysis",
        "",
        f"Source: `{source}`",
        "",
        "Status: generated by `analyze_pool_hopping_sweep.py`.",
        "",
        "## Executive Read",
        "",
        "This report separates two different questions:",
        "",
        "1. **Absolute EV vs theoretical network hashrate EV**: did the hopper earn more than its fair Bitcoin-network share after all GridPool and external mining payouts?",
        "2. **Paired delta vs honest GridPool baseline**: did the hopping strategy outperform an always-on GridPool miner on the same Monte Carlo seed path?",
        "",
        "The paired delta is useful for detecting strategy effects, but it can look large when the honest GridPool path is unlucky. The absolute EV ratio is the safer public-facing number.",
        "",
        "## Run Shape",
        "",
        f"- Variants: `{len(variants)}`",
        f"- Target miner: `{target_miner}`",
        f"- External fees tested: `{', '.join(fees)}`",
        f"- External payout modes tested: `{', '.join(modes)}`",
        "",
        "## Inactive Slot Burden",
        "",
        "These rows estimate how much of the active payout list is owed to miners that are no longer actively mining GridPool under the strategy. This is the cleanest first-pass proxy for the psychological/economic concern behind pool hopping: stale earned claims remaining in the payout template.",
        "",
        "| Variant | External Mode | External Fee | Strategy | Mean Inactive Snapshot Slots | Mean Inactive Snapshot Fraction | Mean Active Team Hashrate Share |",
        "| --- | --- | ---: | --- | ---: | ---: | ---: |",
    ]

    burden_rows = unique_strategy_rows(rows)
    for row in burden_rows:
        inactive_slots = number_or_nan(row, "mean_inactive_snapshot_slots")
        inactive_fraction = number_or_nan(row, "mean_inactive_snapshot_fraction")
        active_share = number_or_nan(row, "mean_active_team_hashrate_share")
        if math.isnan(inactive_slots) and math.isnan(inactive_fraction) and math.isnan(active_share):
            continue
        lines.append(
            "| `{variant}` | `{mode}` | {fee} | `{strategy}` | {slots:.3f} | {fraction:.4f} | {active:.4f} |".format(
                variant=row.get("variant", ""),
                mode=row.get("param_external_payout_mode", "deterministic_fpps"),
                fee=row.get("param_external_fee_rate", ""),
                strategy=row.get("result_label", ""),
                slots=0.0 if math.isnan(inactive_slots) else inactive_slots,
                fraction=0.0 if math.isnan(inactive_fraction) else inactive_fraction,
                active=0.0 if math.isnan(active_share) else active_share,
            )
        )

    lines.extend(
        [
            "",
        "## Honest Calibration",
        "",
        "| Variant | Mean Honest EV Ratio | Min | Max | Mean Pool Blocks |",
        "| --- | ---: | ---: | ---: | ---: |",
        ]
    )

    for variant in variants:
        honest = [
            row
            for row in rows
            if row["variant"] == variant
            and row["result_label"] == "honest_all_miners"
            and row["entity_type"] == "miner"
        ]
        if not honest:
            continue
        ev = [number(row, "metric_primary") for row in honest]
        pool_blocks = number(honest[0], "mean_pool_blocks")
        lines.append(
            f"| `{variant}` | {mean(ev):.6f} | {min(ev):.6f} | {max(ev):.6f} | {pool_blocks:.2f} |"
        )

    lines.extend(
        [
            "",
            "## Hopper Absolute EV",
            "",
            "Values below are BTC earned by the target miner divided by theoretical gross network-hashrate EV. Values above `1.0` mean the strategy beat fair network EV in this model; values below `1.0` mean it underperformed.",
            "",
            "| External Mode | External Fee | Strategy | Average EV Ratio | Min | Max |",
            "| --- | ---: | --- | ---: | ---: | ---: |",
        ]
    )

    for mode in modes:
        for fee in fees:
            for strategy in sorted(
                {
                    row["result_label"]
                    for row in rows
                    if row.get("entity_type") == "miner"
                    and row.get("entity") == target_miner
                    and row.get("param_external_fee_rate", "") == fee
                    and row.get("param_external_payout_mode", "deterministic_fpps") == mode
                }
            ):
                vals = [
                    number(row, "metric_primary")
                    for row in rows
                    if row.get("entity_type") == "miner"
                    and row.get("entity") == target_miner
                    and row.get("result_label") == strategy
                    and row.get("param_external_fee_rate", "") == fee
                    and row.get("param_external_payout_mode", "deterministic_fpps") == mode
                ]
                if vals:
                    lines.append(
                        f"| `{mode}` | {fee} | `{strategy}` | {mean(vals):.6f} | {min(vals):.6f} | {max(vals):.6f} |"
                    )

    lines.extend(
        [
            "",
            "## Hopper Paired Delta Vs Honest GridPool",
            "",
            "This table uses common seeds where available. A positive paired delta means the target miner beat the always-on GridPool baseline on the same seed path. This is good for identifying strategy effects, but not sufficient by itself to claim positive absolute EV.",
            "",
            "| External Mode | External Fee | Strategy | N | Average Delta EV Ratio | Range | CI Above Zero | CI Crosses Zero |",
            "| --- | ---: | --- | ---: | ---: | ---: | ---: | ---: |",
        ]
    )

    for mode in modes:
        for fee in fees:
            for strategy in strategies:
                strategy_rows = [
                    row
                    for row in rows
                    if row.get("entity_type") == "paired_delta"
                    and row.get("entity") == target_miner
                    and row.get("result_label") == strategy
                    and row.get("param_external_fee_rate", "") == fee
                    and row.get("param_external_payout_mode", "deterministic_fpps") == mode
                ]
                if not strategy_rows:
                    continue
                vals = [number(row, "mean_delta_ev_ratio") for row in strategy_rows]
                lows = [number(row, "ci95_delta_ev_ratio_low") for row in strategy_rows]
                highs = [number(row, "ci95_delta_ev_ratio_high") for row in strategy_rows]
                ns = [int(number(row, "paired_n")) for row in strategy_rows]
                ci_rows = [
                    (low, high)
                    for low, high, n in zip(lows, highs, ns)
                    if n >= 2 and not math.isnan(low) and not math.isnan(high)
                ]
                if ci_rows:
                    above_zero = f"{sum(1 for low, _ in ci_rows if low > 0)}/{len(ci_rows)}"
                    crosses_zero = f"{sum(1 for low, high in ci_rows if low <= 0 <= high)}/{len(ci_rows)}"
                else:
                    above_zero = "n/a"
                    crosses_zero = "n/a"
                lines.append(
                    f"| `{mode}` | {fee} | `{strategy}` | {min(ns)}-{max(ns)} | {mean(vals):+.6f} | [{min(vals):+.6f}, {max(vals):+.6f}] | {above_zero} | {crosses_zero} |"
                )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- If the hopper has a zero-fee, deterministic FPPS-like outside option, hopping can look mildly attractive because old GridPool proofs remain payable while outside mining earns expected value elsewhere.",
            "- If the outside option charges realistic fees, that edge should shrink or disappear.",
            "- If the outside option is solo mining, expected value may be similar but variance changes sharply; use longer runs before making a public claim from solo-mode output.",
            "- This model does not add proof decay, identity rules, or punitive behavior. It intentionally tests vanilla GridPool mechanics.",
            "",
            "## Public Claim Template",
            "",
            "> In the published GridPool pool-hopping simulations, tested hopping strategies did not show a meaningful positive absolute EV under realistic external-pool fees. A zero-fee deterministic FPPS outside option can create a small free-option effect because earned GridPool proofs remain payable while the miner temporarily earns elsewhere. That is a variance/liquidity tradeoff, not a way to forge unpaid work or steal other miners' shares.",
            "",
        ]
    )

    target_share_rows = [
        row
        for row in rows
        if row.get("entity_type") == "miner"
        and row.get("entity") == target_miner
        and not math.isnan(number_or_nan(row, "target_miner_hashrate_share"))
    ]
    target_shares = sorted({number_or_nan(row, "target_miner_hashrate_share") for row in target_share_rows})
    if len(target_shares) > 1:
        insert_at = lines.index("## Interpretation")
        detail_lines = build_target_share_detail(rows, target_miner)
        lines[insert_at:insert_at] = detail_lines

    return "\n".join(lines)


def unique_strategy_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    seen = set()
    result = []
    for row in rows:
        if row.get("entity_type") != "miner":
            continue
        key = (
            row.get("variant", ""),
            row.get("result_label", ""),
            row.get("param_external_payout_mode", ""),
            row.get("param_external_fee_rate", ""),
        )
        if key in seen:
            continue
        seen.add(key)
        result.append(row)
    return sorted(result, key=lambda item: (item.get("variant", ""), item.get("result_label", "")))


def build_target_share_detail(rows: list[dict[str, str]], target_miner: str) -> list[str]:
    lines = [
        "",
        "## Target Share Detail",
        "",
        "These rows are useful for solo-outside sweeps where the target miner's share of the GridPool team varies. `Target Share` is the target miner's hashrate divided by total GridPool team hashrate in that variant.",
        "",
        "| External Mode | External Fee | Target Share | Strategy | Absolute EV Ratio | Paired Delta EV Ratio | 95% CI Delta EV Ratio |",
        "| --- | ---: | ---: | --- | ---: | ---: | ---: |",
    ]
    miner_rows = [
        row
        for row in rows
        if row.get("entity_type") == "miner"
        and row.get("entity") == target_miner
    ]
    paired_rows = [
        row
        for row in rows
        if row.get("entity_type") == "paired_delta"
        and row.get("entity") == target_miner
    ]
    paired_by_key = {
        (
            row.get("param_external_payout_mode", "deterministic_fpps"),
            row.get("param_external_fee_rate", ""),
            row.get("target_miner_hashrate_share", ""),
            row.get("result_label", ""),
        ): row
        for row in paired_rows
    }
    for row in sorted(
        miner_rows,
        key=lambda item: (
            item.get("param_external_payout_mode", ""),
            floatish(item.get("param_external_fee_rate", "")),
            number_or_nan(item, "target_miner_hashrate_share"),
            item.get("result_label", ""),
        ),
    ):
        if row.get("result_label") == "honest_all_miners":
            continue
        share = number_or_nan(row, "target_miner_hashrate_share")
        if math.isnan(share):
            continue
        key = (
            row.get("param_external_payout_mode", "deterministic_fpps"),
            row.get("param_external_fee_rate", ""),
            row.get("target_miner_hashrate_share", ""),
            row.get("result_label", ""),
        )
        paired = paired_by_key.get(key, {})
        ci_low = number_or_nan(paired, "ci95_delta_ev_ratio_low")
        ci_high = number_or_nan(paired, "ci95_delta_ev_ratio_high")
        ci = "n/a" if math.isnan(ci_low) or math.isnan(ci_high) else f"[{ci_low:+.6f}, {ci_high:+.6f}]"
        delta = number_or_nan(paired, "mean_delta_ev_ratio")
        delta_text = "n/a" if math.isnan(delta) else f"{delta:+.6f}"
        lines.append(
            "| `{mode}` | {fee} | {share:.1%} | `{strategy}` | {ev:.6f} | {delta} | {ci} |".format(
                mode=row.get("param_external_payout_mode", "deterministic_fpps"),
                fee=row.get("param_external_fee_rate", ""),
                share=share,
                strategy=row.get("result_label", ""),
                ev=number(row, "metric_primary"),
                delta=delta_text,
                ci=ci,
            )
        )
    return lines


def number(row: dict[str, str], key: str) -> float:
    raw = row.get(key, "")
    if raw == "":
        return math.nan
    return float(raw)


def number_or_nan(row: dict[str, str], key: str) -> float:
    raw = row.get(key, "")
    if raw == "":
        return math.nan
    try:
        return float(raw)
    except ValueError:
        return math.nan


def floatish(value: str) -> float:
    try:
        return float(value)
    except ValueError:
        return 0.0


if __name__ == "__main__":
    raise SystemExit(main())
