from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

from .adversary import AdversaryRunResult, aggregate_adversary_results


def write_adversary_reports(
    out_dir: Path,
    scenario: dict[str, Any],
    results: list[AdversaryRunResult],
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    summary = {
        "scenario": scenario,
        "aggregate": aggregate_adversary_results(results),
        "expected_network_ev_by_miner": expected_network_ev_by_miner(scenario),
        "runs": [result_to_dict(result) for result in results],
    }
    (out_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    write_adversary_csv(out_dir / "miner_results.csv", summary)
    write_adversary_markdown(out_dir / "report.md", scenario, summary)


def result_to_dict(result: AdversaryRunResult) -> dict[str, Any]:
    return {
        "label": result.label,
        "seed": result.seed,
        "blocks": result.blocks,
        "pool_blocks": result.pool_blocks,
        "metadata": result.metadata,
        "miners": {
            miner_id: ledger.__dict__
            for miner_id, ledger in result.miners.items()
        },
        "teams": {
            team_id: {
                "blocks_won": team.blocks_won,
                "empty_snapshot_blocks": team.empty_snapshot_blocks,
                "final_work_set_count": len(team.work_set),
                "final_snapshot_count": len(team.active_snapshot),
            }
            for team_id, team in result.teams.items()
        },
    }


def write_adversary_csv(path: Path, summary: dict[str, Any]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "label",
                "miner_id",
                "role",
                "hashrate",
                "mean_btc",
                "gross_hashrate_ev_btc",
                "ev_ratio",
                "std_btc",
                "mean_slot0_btc",
                "mean_shared_btc",
                "mean_block_finds",
                "mean_shares_submitted",
                "mean_shares_accepted",
                "mean_shares_rejected_by_team",
                "mean_snapshot_slot_observations",
            ]
        )
        expected = summary["expected_network_ev_by_miner"]
        for label, data in summary["aggregate"].items():
            for miner_id, miner in data["miners"].items():
                expected_btc = float(expected.get(miner_id, 0.0))
                ev_ratio = miner["mean_btc"] / expected_btc if expected_btc > 0 else 0.0
                writer.writerow(
                    [
                        label,
                        miner_id,
                        miner["role"],
                        miner["hashrate"],
                        f"{miner['mean_btc']:.12f}",
                        f"{expected_btc:.12f}",
                        f"{ev_ratio:.8f}",
                        f"{miner['std_btc']:.12f}",
                        f"{miner['mean_slot0_btc']:.12f}",
                        f"{miner['mean_shared_btc']:.12f}",
                        f"{miner['mean_block_finds']:.8f}",
                        f"{miner['mean_shares_submitted']:.8f}",
                        f"{miner['mean_shares_accepted']:.8f}",
                        f"{miner['mean_shares_rejected_by_team']:.8f}",
                        f"{miner['mean_snapshot_slot_observations']:.8f}",
                    ]
                )


def write_adversary_markdown(path: Path, scenario: dict[str, Any], summary: dict[str, Any]) -> None:
    lines = []
    lines.append(f"# GridPool Majority/Censorship Report: {scenario.get('name', 'unnamed')}")
    lines.append("")
    lines.append("Status: generated by `run_adversary_simulation.py`.")
    lines.append("")
    lines.append("## Scenario")
    lines.append("")
    lines.append("| Parameter | Value |")
    lines.append("| --- | ---: |")
    for key in [
        "blocks",
        "replications",
        "pool_network_share",
        "shares_per_network_block_at_full_team",
        "shared_slots",
        "reserve_multiplier",
    ]:
        if key in scenario:
            lines.append(f"| `{key}` | `{scenario[key]}` |")
    lines.append("")
    lines.append("## Team Outcomes")
    lines.append("")
    lines.append("| Label | Team | Mean Blocks Won | Mean Final Work Set | Mean Final Snapshot |")
    lines.append("| --- | --- | ---: | ---: | ---: |")
    for label, data in summary["aggregate"].items():
        for team_id, team in data["teams"].items():
            lines.append(
                "| {label} | `{team_id}` | {blocks:.3f} | {work:.1f} | {snap:.1f} |".format(
                    label=label,
                    team_id=team_id,
                    blocks=team["mean_blocks_won"],
                    work=team["mean_final_work_set_count"],
                    snap=team["mean_final_snapshot_count"],
                )
            )
    lines.append("")
    lines.append("## Miner Outcomes")
    lines.append("")
    lines.append(
        "| Label | Miner | Role | Mean BTC | Gross Hashrate EV BTC | EV Ratio | Std BTC | Slot0 BTC | Shared BTC | Blocks Found | Shares Accepted | Shares Rejected By Team | Snapshot Slots Observed |"
    )
    lines.append("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    expected = summary["expected_network_ev_by_miner"]
    for label, data in summary["aggregate"].items():
        for miner_id, miner in data["miners"].items():
            expected_btc = float(expected.get(miner_id, 0.0))
            ev_ratio = miner["mean_btc"] / expected_btc if expected_btc > 0 else 0.0
            lines.append(
                "| {label} | `{miner}` | {role} | {btc:.8f} | {expected:.8f} | {ratio:.4f} | {std:.8f} | {slot0:.8f} | {shared:.8f} | {blocks:.3f} | {accepted:.1f} | {rejected:.1f} | {slots:.1f} |".format(
                    label=label,
                    miner=miner_id,
                    role=miner["role"],
                    btc=miner["mean_btc"],
                    expected=expected_btc,
                    ratio=ev_ratio,
                    std=miner["std_btc"],
                    slot0=miner["mean_slot0_btc"],
                    shared=miner["mean_shared_btc"],
                    blocks=miner["mean_block_finds"],
                    accepted=miner["mean_shares_accepted"],
                    rejected=miner["mean_shares_rejected_by_team"],
                    slots=miner["mean_snapshot_slot_observations"],
                )
            )
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- This is a two-team abstraction, not a full peer-network model.")
    lines.append("- The censoring team cannot steal rejected proofs; it can only refuse to count them in its own payout state.")
    lines.append("- Rational non-cartel miners should not keep mining a team that systematically rejects their valid proofs.")
    lines.append("- `naive_target_mines_excluding_team` is included as a warning case for bad client/operator behavior, not as desired protocol behavior.")
    lines.append("- Separate Monte Carlo streams are used per label; compare EV ratios and longer sweeps, not tiny label-to-label differences.")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def expected_network_ev_by_miner(scenario: dict[str, Any]) -> dict[str, float]:
    total_hashrate = sum(float(miner["hashrate"]) for miner in scenario["miners"])
    network_hashrate = total_hashrate / float(scenario["pool_network_share"])
    block_value = float(scenario.get("subsidy_btc", 3.125)) + float(scenario.get("fees_btc", 0.0))
    blocks = int(scenario["blocks"])
    return {
        miner["id"]: (float(miner["hashrate"]) / network_hashrate) * block_value * blocks
        for miner in scenario["miners"]
    }

