from __future__ import annotations

import csv
import json
from pathlib import Path
from statistics import mean
from typing import Any

from .variance import VarianceResult


def write_variance_reports(
    out_dir: Path,
    scenario: dict[str, Any],
    results: list[VarianceResult],
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    summary = {
        "scenario": scenario,
        "aggregate": aggregate_variance_results(results),
        "rows": [result_to_dict(result) for result in results],
    }
    (out_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    write_variance_csv(out_dir / "variance_results.csv", results)
    write_variance_markdown(out_dir / "report.md", scenario, results, summary)


def aggregate_variance_results(results: list[VarianceResult]) -> dict[str, Any]:
    by_slots: dict[int, list[VarianceResult]] = {}
    by_team_multiplier: dict[float, list[VarianceResult]] = {}
    for result in results:
        by_slots.setdefault(result.total_slots, []).append(result)
        by_team_multiplier.setdefault(result.team_multiplier, []).append(result)

    return {
        "by_total_slots": {
            str(total_slots): {
                "mean_grid_variance_reduction_vs_solo": mean(r.grid_variance_reduction_vs_solo for r in rows),
                "mean_grid_cv_reduction_vs_solo": mean(r.grid_cv_reduction_vs_solo for r in rows),
                "mean_probability_zero_grid_payout": mean(r.probability_zero_grid_payout for r in rows),
            }
            for total_slots, rows in sorted(by_slots.items())
        },
        "by_team_multiplier": {
            format_number(team_multiplier): {
                "mean_grid_variance_reduction_vs_solo": mean(r.grid_variance_reduction_vs_solo for r in rows),
                "mean_grid_cv_reduction_vs_solo": mean(r.grid_cv_reduction_vs_solo for r in rows),
                "mean_probability_zero_grid_payout": mean(r.probability_zero_grid_payout for r in rows),
            }
            for team_multiplier, rows in sorted(by_team_multiplier.items())
        },
    }


def result_to_dict(result: VarianceResult) -> dict[str, Any]:
    return result.__dict__.copy()


def write_variance_csv(path: Path, results: list[VarianceResult]) -> None:
    rows = [result_to_dict(result) for result in results]
    fieldnames = [
        "miner_id",
        "miner_hashrate_eh",
        "expected_solo_blocks",
        "team_multiplier",
        "team_network_share",
        "team_expected_blocks",
        "total_slots",
        "shared_slots",
        "slot_value_btc",
        "slot0_value_btc",
        "expected_slots_per_team_block",
        "expected_shared_slots_per_period",
        "probability_zero_shared_slots",
        "probability_zero_grid_payout",
        "solo_mean_btc",
        "solo_std_btc",
        "solo_cv",
        "solo_probability_zero_payout",
        "fpps_mean_btc",
        "fpps_std_btc",
        "fpps_cv",
        "grid_mean_btc",
        "grid_std_btc",
        "grid_cv",
        "grid_variance_reduction_vs_solo",
        "grid_cv_reduction_vs_solo",
        "grid_effective_independent_payout_units",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_variance_markdown(
    path: Path,
    scenario: dict[str, Any],
    results: list[VarianceResult],
    summary: dict[str, Any],
) -> None:
    lines = []
    lines.append(f"# GridPool Payout Variance Report: {scenario.get('name', 'unnamed')}")
    lines.append("")
    lines.append("Status: generated by `run_variance_analysis.py`.")
    lines.append("")
    lines.append("## Scenario")
    lines.append("")
    lines.append("| Parameter | Value |")
    lines.append("| --- | ---: |")
    for key in [
        "period_label",
        "period_network_blocks",
        "reference_network_hashrate_eh",
        "subsidy_btc",
        "fees_btc",
        "fpps_fee_rate",
        "support_slot_enabled",
    ]:
        if key in scenario:
            lines.append(f"| `{key}` | `{scenario[key]}` |")
    lines.append("")
    lines.append("## Slot Count Summary")
    lines.append("")
    lines.append("| Total Slots | Mean Variance Reduction vs Solo | Mean CV Reduction vs Solo | Mean Zero Grid Payout Probability |")
    lines.append("| ---: | ---: | ---: | ---: |")
    for total_slots, data in summary["aggregate"]["by_total_slots"].items():
        lines.append(
            "| {slots} | {var:.3f}x | {cv:.3f}x | {zero:.4%} |".format(
                slots=total_slots,
                var=data["mean_grid_variance_reduction_vs_solo"],
                cv=data["mean_grid_cv_reduction_vs_solo"],
                zero=data["mean_probability_zero_grid_payout"],
            )
        )
    lines.append("")
    lines.append("## Selected Rows")
    lines.append("")
    lines.append(
        "| Miner | Team x Miner | Slots | Team Blocks / Period | Grid Mean BTC | Grid CV | Solo CV | Variance Reduction | Zero Grid Payout | Expected Shared Slots / Period |"
    )
    lines.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for result in results[:240]:
        lines.append(
            "| `{miner}` | {team}x | {slots} | {team_blocks:.4f} | {grid_mean:.8f} | {grid_cv:.4f} | {solo_cv:.4f} | {reduction:.2f}x | {zero:.4%} | {shared_slots:.4f} |".format(
                miner=result.miner_id,
                team=format_number(result.team_multiplier),
                slots=result.total_slots,
                team_blocks=result.team_expected_blocks,
                grid_mean=result.grid_mean_btc,
                grid_cv=result.grid_cv,
                solo_cv=result.solo_cv,
                reduction=result.grid_variance_reduction_vs_solo,
                zero=result.probability_zero_grid_payout,
                shared_slots=result.expected_shared_slots_per_period,
            )
        )
    if len(results) > 240:
        lines.append(f"| ... | ... | ... | ... | ... | ... | ... | ... | ... | {len(results) - 240} more rows in CSV |")
    lines.append("")
    lines.append("## Model")
    lines.append("")
    lines.append("- The utility metric is actual payout BTC over a fixed period, not snapshot inclusion by itself.")
    lines.append("- A miner with team share `p` receives approximately `Binomial(K, p)` shared payout slots per GridPool block, where `K` is the number of shared slots.")
    lines.append("- GridPool blocks arrive as a Poisson process. If the team grows while the miner's hashrate is fixed, team blocks become more frequent and `p` shrinks; those effects cancel in expected BTC.")
    lines.append("- Variance still changes with team size because payouts are less clumped when a miner owns a smaller fraction of a larger team.")
    lines.append("- Pure solo is modeled as Poisson block discovery by the miner. FPPS is modeled as deterministic expected value before pool counterparty risk and payout-policy details.")
    lines.append("- Fees are included in the slot-0 reward, so high transaction fees reduce variance improvement versus a fee-free idealization.")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def format_number(value: float) -> str:
    if value.is_integer():
        return str(int(value))
    return f"{value:g}"
